# Generated by ./update.sh - do not update manually!
# Last updated: 2023-07-31
{
  compatList = {
    rev = "c7edd3cd29fbcc6cf852b5d45e9748625d4e9eda";
    hash = "sha256:1hdsza3wf9a0yvj6h55gsl7xqvhafvbz1i8paz9kg7l49b0gnlh1";
  };

  mainline = {
    version = "1512";
    hash = "sha256:06hri87jxwwnwc6p0w4py9n5924znjw2zl98nsfvzx6c7wwsrb1c";
  };

  ea = {
    version = "3782";
    distHash = "sha256:0b2i5gy29qw6fv70sphlxva9n2alchkrmi31j4zgh0f6ry4s448y";
    fullHash = "sha256:11hjxqd7yi3xgh69n33cwzn5nblq11x9shfgjr0flvipsg4cqf3b";
  };
}
