# Generated by ./update.sh - do not update manually!
# Last updated: 2023-05-29
{
  compatList = {
    rev = "c82c9326af2174c1517b93e7d89bd17fafb2259e";
    hash = "sha256:1hdsza3wf9a0yvj6h55gsl7xqvhafvbz1i8paz9kg7l49b0gnlh1";
  };

  mainline = {
    version = "1450";
    hash = "sha256:1dmk0asrhvkd3cnng4bw294shcy9j3dd4kcsycam2vdvr08v5yb8";
  };

  ea = {
    version = "3621";
    distHash = "sha256:0p8rxpwn9f269008skj7dy6qinpax93jhp33769akrprbh7f22if";
    fullHash = "sha256:1ph8frqifk42ypa0fw604k1z4kjisl35cai830cg4zhvd0vv7rn5";
  };
}
