# Generated by ./update.sh - do not update manually!
# Last updated: 2023-07-24
{
  compatList = {
    rev = "34f5d8d22501b6df70f3c73e9e1f3e67b939a678";
    hash = "sha256:1hdsza3wf9a0yvj6h55gsl7xqvhafvbz1i8paz9kg7l49b0gnlh1";
  };

  mainline = {
    version = "1505";
    hash = "sha256:0l9164k7nfylczs9b610ns15fz3vvydysd0m1rzqy4nqnp8ajx8f";
  };

  ea = {
    version = "3777";
    distHash = "sha256:0sccrglb19bw0ng3mdgqczfy76p8hdv0cyacis9w3if7kynnqygb";
    fullHash = "sha256:0lb8knnmrd9hc45ybddlwvlxzw6i6dlhk28psry6ns18lgz014f0";
  };
}
