name: "Build"

on:
  # Build on push to master
  push:
    branches:
      - master

  # Build on internal pull requests
  pull_request:

  # Allow to trigger for external PRs
  workflow_dispatch:

  # Also run regularly because pushes initiated by GitHub Actions don't
  # trigger the above events.
  # schedule:
  #   # every day at 8am UTC
  #   - cron: '10 8 * * *'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
      # with:
      #   extra_nix_config: |
      #     access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: leiserfg
        authToken: '${{ secrets.CACHIX_TOKEN }}'
    - run: git clone 'https://git.citron-emu.org/Citron/Citron.git'
    - run: nix flake show --json | jq  '.packages."x86_64-linux"|keys[]'| xargs -I {} nix build .#{}
